cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: us-west-2
    endpoint: http://localhost:9090
    stack:
      auto: false

application:
  bucket:
    name: fitstorebucket

server:
  port: 8080
