version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - fitstore:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fitstore
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
volumes:
  fitstore: