version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
      - s3mock
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
  db:
    image: postgres
    restart: always
    volumes:
      - fitstore:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fitstore
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
  s3mock:
    image: adobe/s3mock:latest
    container_name: s3mock
    environment:
      - initialBuckets=fitstorebucket
      - root=/data
      - retainFilesOnExit=true
    ports:
      - 9090:9090
    volumes:
      - ./s3mock-data:/data

volumes:
  fitstore: