CREATE TABLE public.customers (
	id uuid NOT NULL,
	street varchar(255) NOT NULL,
	house_number varchar(255) NOT NULL,
    complement varchar(255) NULL,
    neighborhood varchar(255) NOT NULL,
	city varchar(255) NOT NULL,
	state varchar(255) NOT NULL,
	cep varchar(255) NOT NULL,
	cpf varchar(255) NOT NULL,
	created_at timestamp(6) NOT NULL,
	email varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	phone_number varchar(255) NOT NULL,
	"role" varchar(255) NOT NULL,
	image_path varchar(255) NULL,
	updated_at timestamp(6) NOT NULL,
	CONSTRAINT customers_pkey PRIMARY KEY (id),
	CONSTRAINT customers_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'ADMIN'::character varying])::text[]))),
	CONSTRAINT customers_cpf_unique UNIQUE (cpf),
	CONSTRAINT customers_email_unique UNIQUE (email)
);