package com.project.fitstore.exceptions;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    INVALID_STATUS_VALUE,
    INTERNAL_ERROR,
    COUPON_NOT_FOUND,
    COUPON_EXPIRED,
    COUPON_NOT_APPLICABLE,
    COUPON_LIMIT_EXCEEDED,
    INVALID_ORDER,
    ORDER_EXPIRED,
    ORDER_NOT_FOUND,
    ORDER_HAS_PAYMENT_RECORD,
    CUSTOMER_NOT_FOUND,
    INCORRECT_CURRENT_PASSWORD,
    SUB_CATEGORY_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    IMAGE_UPLOAD_ERROR,
    IMAGE_DELETE_ERROR,
    INVALID_CREDENTIALS,
    DUPLICATE_FIELD
}
